services:

  mariadb:
    image: mariadb:11.5.2-noble
    container_name: mariadb_event_buddy
    restart: unless-stopped
    networks:
      event-buddy:
    ports:
      - "$MYSQL_PORT:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    volumes:
      - event-buddy-mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_event_buddy
    restart: unless-stopped
    networks:
      event-buddy:
    ports:
      - "$PHPMYADMIN_PORT:80"
    environment:
      PMA_HOST: "mariadb"
      PMA_PORT: "3306"

volumes:
  event-buddy-mariadb:
    name: event-buddy-mariadb

networks:
  event-buddy:
